### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by TobbyTravel** [hartfelt/kiara#7]
Hi,

This script seem like it might fit my usecase.
I have a folder with all my anime and want to add it to anidb, but I get error that xxxfolder is not a file. Is it possible to run it on a folder+subfolder?

Can you perhaps add a some examples?
Here are some lines I ran during installation that might help others.

sudo apt-get install python3-distutils
git clone https://github.com/hartfelt/kiara --depth 1 --branch=master ~/kiara
mv ~/kiararc/kiararc ~/.kiararc

**Comment by hartfelt** [comment]
Hi,
You can combine it with `find` to run it on each file, something like:

`find your/root/anime/dir -type f -exec kiara {} \;`

if your files are nested in different levels.

If all the files are at the same level, you can just do:

`kiara your/root/anime/dir/*`

**Comment by TobbyTravel** [comment]
Thank you
